/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.flexibook.application;

import java.sql.Date;
import java.sql.Time;

import ca.mcgill.ecse.flexibook.model.FlexiBook;
import ca.mcgill.ecse.flexibook.model.User;
import ca.mcgill.ecse.flexibook.util.SystemTime;

public class FlexiBookApplication {
	private static FlexiBook flexiBook;
    private static User currentUser;
    private static SystemTime systemTime;
	
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new FlexiBookApplication().getGreeting());
    }
    
    public static FlexiBook getFlexiBook() {
    	if (flexiBook == null) {
    		flexiBook = new FlexiBook();
    	}
    	
    	return flexiBook;
    }
    
    public static boolean hasCurrentUser() {
    	return currentUser != null;
    }
    
    public static User getCurrentUser() {
    	return currentUser;
    }
    
    public static void setCurrentUser(User user) {
    	if (user == null) {
    		throw new IllegalArgumentException("Current user cannot be set to null"); // use #unsetCurrentUser
    	}
    	currentUser = user;
    }
    
    public static void unsetCurrentUser() {
    	currentUser = null;
    }

    public static SystemTime getSystemTime(){
        if(systemTime == null){
            systemTime = new SystemTime();
        }
        return systemTime;
    }

    public static void setSystemTime(boolean isTesting, Date date, Time time){
        if(isTesting){
            SystemTime.setTesting(date, time);
        }
        else{
            systemTime = new SystemTime();
        }
    }
}
